apiVersion: v1
kind: Service
metadata:
  name: svc-simple-demo
  labels:
    app: simple-demo
spec:
  selector:
    app: mi-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
